// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afthptfyvzkzvjndmpjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdGhwdGZ5dnprenZqbmRtcGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTY2NTAsImV4cCI6MjA3MDQzMjY1MH0.jOT9LbMdEE59Z2qaNN44vbDdvMgsnhZmsT_ZnzAqMLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});